name: Deploy to EC2 from FE

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push to Docker image to aditya-resume-frontend
      run: |
        IMAGE_NAME=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
        docker build \
          --build-arg GOOGLE_RECAPTCHA_V3_SITE_KEY=${{ secrets.GOOGLE_RECAPTCHA_V3_SITE_KEY }} \
          -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "restarting the application..."
          sudo docker-compose down || true
          echo "removing all stopped containers"
          sudo docker container prune -f || true
          echo "removing the existing image on the server"
          sudo docker rmi docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest || true
          echo "pulling the latest image from docker hub"
          sudo docker pull docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
          echo "restarting the application"
          sudo docker-compose up -d
